
---
- name: Postgres DB Config with optimization
  hosts: all
  become: true
  tasks:
    - name: Update package cache (RedHat)
      dnf:
        update_cache: yes

    - name: Install PostgreSQL repository (RedHat)
      command: "sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"

    - name: Disable PostgreSQL module (RedHat)
      command: "sudo dnf -qy module disable postgresql"

    - name: Install PostgreSQL 14 server (RedHat)
      dnf:
        name: "postgresql14-server"
        state: present

    - name: Initialize PostgreSQL 14 database
      command: "sudo /usr/pgsql-14/bin/postgresql-14-setup initdb"

    - name: Enable PostgreSQL 14 service
      systemd:
        name: "postgresql-14"
        enabled: yes
